version: '3.8'

services:
  api:
    image: ${DOCKER_USERNAME}/furniture-api:latest
    container_name: furniture-api-container
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=5000
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=http://${VPS_HOST}:3000 , https://everwoodcollection.com
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BREVO_SENDER_EMAIL=${BREVO_SENDER_EMAIL}
      - BREVO_SENDER_NAME=${BREVO_SENDER_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    restart: unless-stopped
    networks:
      - furniture-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  client:
    image: ${DOCKER_USERNAME}/furniture-client:latest
    container_name: furniture-client-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SUPABASE_BUCKET=${NEXT_PUBLIC_SUPABASE_BUCKET}
    depends_on:
      api:
        condition: service_started
    restart: unless-stopped
    networks:
      - furniture-network

networks:
  furniture-network:
    driver: bridge